openapi: '3.0.0'
info:
  version: 1.0.0
  title: Data Types API

paths:
  /types:
    x-apigen-binding:
      model: EntityTypes
    post:
      operationId: createType
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/new_type"
      responses:
        '201':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/standard_response_type"
  /types/{id}:
    x-apigen-binding:
      model: EntityTypes
    get:
      operationId: getType
      parameters:
        - $ref: "#/components/parameters/integer_id_param"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/standard_response_type"

components:
  parameters:
    integer_id_param:
      in: path
      name: id
      required: true
      schema:
        type: integer
        format: int64

  schemas:
    standard_response_result:
      properties:
        result:
          type: object
          properties:
            status:
              type: boolean
            http_code:
              type: integer
            errors:
              type: array
              items:
                $ref: '#/components/schemas/standard_error'
            info:
              type: string
            trace_id:
              type: string
            num_elements:
              type: integer
          required:
            - status
            - http_code
            - trace_id
    standard_error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    standard_response_type:
      allOf:
        - $ref: "#/components/schemas/standard_response_result"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/type"
    type:
      x-apigen-mapping:
        model: EntityTypes
      allOf:
        - $ref: '#/components/schemas/new_type'
        - type: object
          properties:
            id:
              type: integer

    new_type:
      x-apigen-mapping:
        model: EntityTypes
      type: object
      properties:
        field_string:
          type: string
        field_boolean:
          type: boolean
        field_float:
          type: number
          format: float
        field_double:
          type: number
          format: double
        field_big_decimal:
          type: number
          format: double
          x-apigen-type: BigDecimal
        field_integer:
          type: integer
          format: int32
        field_long:
          type: integer
          format: int64
        field_big_integer:
          type: integer
          format: int64
          x-apigen-type: BigInteger
        field_date:
          type: string
          format: date
        field_datetime:
          type: string
          format: date-time
        field_zoned_datetime:
          type: string
          format: date-time
          x-apigen-type: ZonedDateTime
        field_local_datetime:
          type: string
          format: date-time
          x-apigen-type: LocalDateTime
        field_instant:
          type: integer
          format: int64
          x-apigen-type: Instant

  x-apigen-models:
    EntityTypes:
      relational-persistence:
        table: types
      attributes:
        - name: id
          type: Long
          relational-persistence:
            column: id
            primary-key: true
            autogenerated: true
        - name: fieldString
          type: String
        - name: fieldBoolean
          type: Boolean
        - name: fieldFloat
          type: Float
        - name: fieldDouble
          type: Double
        - name: fieldBigDecimal
          type: BigDecimal
        - name: fieldInteger
          type: Integer
        - name: fieldLong
          type: Long
        - name: fieldBigInteger
          type: BigInteger
        - name: fieldDate
          type: LocalDate
        - name: fieldDatetime
          type: OffsetDateTime
        - name: fieldZonedDatetime
          type: ZonedDateTime
        - name: fieldLocalDatetime
          type: LocalDateTime
        - name: fieldInstant
          type: Instant

x-apigen-project:
  name: dataTypes
  description: description
  version: 1.0.0
  java-properties:
    group-id: the.group
    artifact-id: app
